/**
 * Embeds the two declaration files the advanced editor needs into the extension bundle.
 *
 * "Transform Selections (Advanced)" writes a scratch `.ts` file into the extension's
 * global storage directory and drops `rt.d.ts` and `convnum.d.ts` next to it, so the
 * user gets hover documentation, completion and type checking over `s`, `n`, `i`, the
 * helpers and the whole convnum API.
 *
 * The extension ships as a single esbuild bundle with no `node_modules`, so those
 * declarations have to travel inside it as strings. `JSON.stringify` is used rather
 * than a template literal because the declarations contain backticks and `${` inside
 * JSDoc examples.
 *
 * `src/usertypes/rt.d.ts` is hand-written and committed — this only copies it.
 * convnum's declarations come from the installed package.
 *
 * Output is generated, not committed. Run via `bun run gen` (also wired to postinstall).
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'

// Always invoked as `bun run gen` from the repository root.
const root = process.cwd()
const outFile = join(root, 'src', 'generated', 'dts.ts')

function resolveConvnumDts(): string {
  const require = createRequire(join(root, 'package.json'))
  // convnum is ESM-first with a CJS condition, so its entry point may be `.cjs`.
  // Resolve the manifest instead and walk to the declarations from there.
  const manifest = require.resolve('convnum/package.json')
  return join(dirname(manifest), 'dist', 'index.d.ts')
}

function read(path: string, hint: string): string {
  try {
    return readFileSync(path, 'utf8')
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error)
    console.error(`Could not read ${path}: ${reason}\n${hint}`)
    process.exit(1)
  }
}

function main(): void {
  const convnumPath = resolveConvnumDts()
  const convnum = read(
    convnumPath,
    'If convnum is a local `file:` dependency, run `bun run build` inside it first.',
  )
    // The .map file is not shipped, and a dangling reference makes the TypeScript
    // server complain inside the user's scratch file.
    .replace(/^\/\/# sourceMappingURL=.*$/gm, '')
    .trimEnd()

  const globals = read(
    join(root, 'src', 'usertypes', 'rt.d.ts'),
    'This file is hand-written and should be committed.',
  ).trimEnd()

  const contents = `// Generated by scripts/genDts.ts — do not edit.

/**
 * The hand-written ambient declarations from \`src/usertypes/rt.d.ts\`, verbatim.
 *
 * Written to \`rt.d.ts\` in the scratch directory; the scratch file's triple-slash
 * reference points at it.
 */
export const RT_GLOBALS_DTS = ${JSON.stringify(globals)}

/**
 * convnum's complete type declarations, verbatim.
 *
 * Written to \`convnum.d.ts\` in the scratch directory so that the \`rt.d.ts\` line
 * \`declare const convnum: typeof import('./convnum')\` resolves. Copying the file
 * unchanged is what makes this robust — no rewriting of TypeScript is involved.
 */
export const CONVNUM_DTS = ${JSON.stringify(convnum)}
`

  mkdirSync(dirname(outFile), { recursive: true })
  writeFileSync(outFile, contents, 'utf8')

  console.log(
    `Generated ${outFile} (${globals.length} + ${convnum.length} characters)`,
  )
}

main()
