name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Check TypeScript types
        run: bun run check-types

      - name: Lint code
        run: bun run lint

      - name: Format check
        run: bun run format:check

      - name: Start virtual display
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Run tests
        run: bun run test

      - name: Compile extension production
        run: bun run compile:prod

      - name: Install publishing tools
        run: npm install -g vsce ovsx

      - name: Validate package
        run: vsce package --no-yarn

      - name: Publish to VS Code Marketplace
        if: github.repository == 'tomchen/vscode-range-transform'
        run: vsce publish -p ${{ secrets.VSCE_TOKEN }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}

      - name: Publish to Open VSX Registry
        if: github.repository == 'tomchen/vscode-range-transform'
        run: ovsx publish -p ${{ secrets.OPENVSX_TOKEN }}

      - name: Upload extension package
        uses: actions/upload-artifact@v4
        with:
          name: extension-package
          path: range-transform-*.vsix
